import Head from "next/head";
import Landing from "./landing";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>🔥Bayngo🔥</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <link
          rel="preload"
          href="/fonts/OstrichSans-Heavy.otf"
          as="font"
          crossOrigin=""
        />
      </Head>
      <Landing />
    </div>
  );
}
