import Head from "next/head";
import Bingo from "./board";
import Image from "next/image";
import Link from "next/link";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>🔥Bayngo🔥</title>
        <meta name="description" content="Generated by create next app" />
        <meta charSet="UTF-8" />
        <link
          rel="preload"
          href="/fonts/OstrichSans-Heavy.otf"
          as="font"
          crossOrigin=""
        />
      </Head>

      <main className={styles.main}>
        <Link href="/board-builder">
          <a>Create</a>
        </Link>
        <Link href="/board-join">
          <a>Join</a>
        </Link>
        <Bingo />
      </main>
    </div>
  );
}
